// No Bats Baseball Club - Members Data
// All member names and their corresponding image files

const membersData = [
  { name: "Alan Abruzzo", image: "abruzzo_alan.png" },
  { name: "Danny Acosta", image: "acosta_danny.png" },
  { name: "Gene Ahlhorn", image: "ahlhorn_gene.png" },
  { name: "Mark Andregg", image: "andregg_mark.png" },
  { name: "Bryson Andregg", image: "nbbclogo.png" },
  { name: "Tanner Andregg", image: "nbbclogo.png" },
  { name: "Brian Arnold", image: "arnold_brian.png" },
  { name: "Chad Arnold", image: "arnold_chad.png" },
  { name: "Bill Bartz", image: "bartz_bill.png" },
  { name: "Kirk Bauer", image: "bauer_kirk.png" },
  { name: "Kyle Beck", image: "beck_kyle.png" },
  { name: "Sean Beck", image: "beck_sean.png" },
  { name: "Clark Bell", image: "bell_clarke.png" },
  { name: "Jon Bellis", image: "bellis_jon.png" },
  { name: "Rich Bellis", image: "bellis_rich.png" },
  { name: "Charlie Blackwell", image: "blackwell_charlie.png" },
  { name: "Dave Bloom", image: "bloom_dave.png" },
  { name: "Jim Blythe", image: "blythe_jim.png" },
  { name: "Bruce Bochy", image: "bochy_bruce.png" },
  { name: "Bill Bouie", image: "bouie_bill.png" },
  { name: "Phil Bouie", image: "bouie_phil.png" },
  { name: "Steve Bouchard", image: "nbbclogo.png" },
  { name: "Trisha Bouchard", image: "nbbclogo.png" },
  { name: "Jon Braun", image: "braun_jon.png" },
  { name: "Eric Brown", image: "brown_eric.png" },
  { name: "Larry Bryan", image: "bryan_larry.png" },
  { name: "Andy Bryant", image: "bryant_andy.png" },
  { name: "Brendan Burke", image: "burke_brendan.png" },
  { name: "Dave Burnett", image: "burnett_dave.png" },
  { name: "Jake Burns", image: "burns_jake.png" },
  { name: "Michael Byrne", image: "byrne_michael.png" },
  { name: "Mike Caldwell", image: "caldwell_mike.png" },
  { name: "Dan Caliguiri", image: "caliguiri_dan.png" },
  { name: "Joe Calvanico", image: "calvanico_joe.png" },
  { name: "Adam Camacho", image: "camacho_adam.png" },
  { name: "Domenic Camarda", image: "camarda_domenic.png" },
  { name: "Francesco Camarda", image: "camarda_francesco.jpg" },
  { name: "Howard Cantrell", image: "cantrell_howard.png" },
  { name: "Rich Cardillo", image: "cardillo_rich.png" },
  { name: "Dan Carroll", image: "carroll_dan.png" },
  { name: "Pat Casper", image: "casper_pat.png" },
  { name: "Dave Cassese", image: "cassese_dave.png" },
  { name: "David Cassese Jr", image: "nbbclogo.png" },
  { name: "Mark Cates", image: "cates_mark.png" },
  { name: "Steve Cauthen", image: "nbbclogo.png" },
  { name: "Eric Chapman", image: "chapman_eric.png" },
  { name: "John Chapman", image: "chapman_john.png" },
  { name: "Bobby Chivera", image: "chivera_bobby.png" },
  { name: "Pete Cianflone", image: "cianflone_pete.png" },
  { name: "Jim Collins", image: "collins_jim.png" },
  { name: "Rafael Coquis", image: "coquis_rafael.png" },
  { name: "Dave Cornell", image: "cornell_dave.png" },
  { name: "Dan Costigan", image: "costigan_dan.png" },
  { name: "John Costigan", image: "costigan_john.png" },
  { name: "Mark Costigan", image: "costigan_mark.png" },
  { name: "Brian Crawford", image: "crawford_brian.png" },
  { name: "Evan Crawford", image: "crawford_evan.png" },
  { name: "Joe Crawford", image: "nbbclogo.png" },
  { name: "Keven Crawford", image: "crawford_keven.png" },
  { name: "Shane Crawford", image: "nbbclogo.png" },
  { name: "Stephen Crawford", image: "crawford_steve.png" },
  { name: "Ted Darby", image: "darby_ted.png" },
  { name: "Claudia Davis", image: "davis_claudia.png" },
  { name: "Emily Davis", image: "davis_emily.png" },
  { name: "Jay Davis", image: "davis_jay.png" },
  { name: "Andre Dawson", image: "dawson_andre.jpg" },
  { name: "Charlie Dayton", image: "dayton_charlie.png" },
  { name: "Brian Deegan", image: "deegan_brian.png" },
  { name: "Matt Dobbins", image: "nbbclogo.png" },
  { name: "Derek Dimmick", image: "dimmick_derek.png" },
  { name: "Scott Doney", image: "doney_scott.png" },
  { name: "Andy Dow", image: "dow_andy.png" },
  { name: "Scott Dow", image: "dow_scott.png" },
  { name: "Dave Dravecky", image: "dravecky_dave.png" },
  { name: "Mark Dreyer", image: "dreyer_mark.png" },
  { name: "Jeremy Dullin", image: "dullin_jeremy.png" },
  { name: "Brian Dusza", image: "dusza_brian.png" },
  { name: "Chris Duzich", image: "duzich_chris.png" },
  { name: "Mike Ebener", image: "ebener_mike.png" },
  { name: "Ryan Ebener", image: "ebener_ryan.png" },
  { name: "Mike Elston", image: "elston_mike.png" },
  { name: "Brock Eubanks", image: "eubanks_brock.png" },
  { name: "Jon Falk", image: "falk_jon.png" },
  { name: "Brad Fawcett", image: "fawcett_brad.png" },
  { name: "Brian Fawcett", image: "fawcett_brian.png" },
  { name: "Mike Flynn", image: "flynn_mike.png" },
  { name: "Chip Ford", image: "ford_chip.png" },
  { name: "Jay Fox", image: "fox_jay.png" },
  { name: "Dave French", image: "french_dave.png" },
  { name: "Mark French", image: "french_mark.png" },
  { name: "Jason Gaca", image: "gaca_jason.jpeg" },
  { name: "Alex Gallegos", image: "gallegos_alex.png" },
  { name: "John Gallegos", image: "gallegos_john.png" },
  { name: "John Gilbert", image: "gilbert_john.png" },
  { name: "Orlando Gill", image: "gill_orlando.png" },
  { name: "John Gilmore", image: "gilmore_john.png" },
  { name: "Israel Gonzalez", image: "gonzalez_israel.png" },
  { name: "JJ Gottsch", image: "gottsch_jj.png" },
  { name: "Mike Guarino", image: "guarino_mike.png" },
  { name: "Tony Gwynn", image: "missing_image.png" },
  { name: "Rob Halcomb", image: "halcomb_rob.png" },
  { name: "Bruce Hall", image: "hall_bruce.png" },
  { name: "Atlee Hammaker", image: "hammaker_atlee.png" },
  { name: "Scott Hammerle", image: "hammerle_scott.png" },
  { name: "Pat Hannan", image: "hannan_pat.png" },
  { name: "Tommy Harrell", image: "harrell_tommy.png" },
  { name: "Randy Hart", image: "hart_randy.png" },
  { name: "Charlie Hook", image: "hook_charlie.png" },
  { name: "Mike Howland", image: "howland_mike.png" },
  { name: "Jim Hunter", image: "missing_image.png" },
  { name: "Ryan Hutchens", image: "hutchens_ryan.jpeg" },
  { name: "John Isaac", image: "isaac_john.png" },
  { name: "Charles Johnson", image: "missing_image.png" },
  { name: "Randy Johnson", image: "missing_image.png" },
  { name: "Steve Johnston", image: "johnston_steve.png" },
  { name: "Brian Jones", image: "jones_brian.png" },
  { name: "Frank Kalata", image: "kalata_frank.png" },
  { name: "Glenn Kalata", image: "kalata_glenn.png" },
  { name: "Harley Kane", image: "kane_harley.png" },
  { name: "Howard Katz", image: "katz_howard.png" },
  { name: "Bob Kedzior", image: "kedzior_bob.png" },
  { name: "Dick Kievit", image: "kievit_dick.png" },
  { name: "Rick Kievit", image: "kievit_rick.png" },
  { name: "Dave Klubock", image: "klubock_dave.png" },
  { name: "Gary Leffke", image: "leffke_gary.png" },
  { name: "George Levitt", image: "levitt_george.png" },
  { name: "Jim Lintzenich", image: "lintzenich_jim.png" },
  { name: "Don Lippert", image: "lippert_don.png" },
  { name: "Dave Maddelena", image: "maddelena_dave.png" },
  { name: "Joe Maiden", image: "maiden_joe.png" },
  { name: "Matt Marqua", image: "marqua_matt.png" },
  { name: "Brad Martin", image: "martin_brad.png" },
  { name: "Matt Martin", image: "martin_matt.png" },
  { name: "Marc Matthews", image: "matthews_marc.png" },
  { name: "Colton Matthews", image: "nbbclogo.png" },
  { name: "Grayson Matthews", image: "nbbclogo.png" },
  { name: "Dylan Mayer", image: "mayer_dylan.png" },
  { name: "Steve Mayer", image: "mayer_steve.png" },
  { name: "Tim Mayer", image: "mayer_tim.png" },
  { name: "Conor Maynard", image: "maynard_conor.png" },
  { name: "Bill McClintock", image: "mcclintock_bill.png" },
  { name: "Mike McGaha", image: "mcgaha_bubba.png" },
  { name: "Ira McKnight", image: "missing_image.png" },
  { name: "Paul McMullen", image: "mcmullen_paul.png" },
  { name: "Hank McRoberts", image: "mcroberts_hank.png" },
  { name: "Henry McRoberts Jr", image: "nbbclogo.png" },
  { name: "Brian Meeks", image: "meeks_brian.png" },
  { name: "Chad Meyers", image: "missing_image.png" },
  { name: "John Miles", image: "missing_image.png" },
  { name: "Don Miller", image: "miller_don.png" },
  { name: "Mike Mitchell", image: "mitchell_mike.png" },
  { name: "Mike Montgomery", image: "montgomery_mike.png" },
  { name: "Steve Moore", image: "moore_steve.png" },
  { name: "Larry Morris", image: "morris_larry.png" },
  { name: "Bob Moyer", image: "moyer_bob.png" },
  { name: "Sasha Muratov", image: "muratov_sasha.png" },
  { name: "Mike Nelson", image: "nelson_mike.png" },
  { name: "Todd Nelson", image: "nelson_todd.png" },
  { name: "Paul Neubert", image: "neubert_paul.png" },
  { name: "John Ohly", image: "ohly_john.png" },
  { name: "Augie Ojeda", image: "missing_image.png" },
  { name: "Gregg Olson", image: "olson_gregg.png" },
  { name: "Mike O'Neil", image: "oneil_mike.png" },
  { name: "Mike O'Neil Jr.", image: "oneil_mike_jr.png" },
  { name: "Scott O'Neil", image: "oneil_scott.png" },
  { name: "Leo Ortiz", image: "ortiz_leo.png" },
  { name: "Mitch Packard", image: "packard_mitch.png" },
  { name: "Aldo Panatonni", image: "panatonni_aldo.png" },
  { name: "Michael Papenberg", image: "papenberg_mike.png" },
  { name: "Nico Petruzzelli", image: "petruzzelli_nico.jpg" },
  { name: "Joe Prado", image: "prado_joe.png" },
  { name: "Steve Prather", image: "prather_steve.png" },
  { name: "Bob Pratt", image: "pratt_bob.png" },
  { name: "Greg Pryor", image: "pryor_greg.png" },
  { name: "Rick Pullano", image: "pullano_rick.png" },
  { name: "Dave Purcell", image: "purcell_dave.png" },
  { name: "Mark Pyle", image: "pyle_mark.png" },
  { name: "Dean Quintas", image: "quintas_dean.png" },
  { name: "Pete Rather", image: "rather_pete.png" },
  { name: "Emmett Reagan", image: "reagan_emmett.png" },
  { name: "Jeff Reardon", image: "missing_image.png" },
  { name: "Murphy Reed", image: "reed_murphy.png" },
  { name: "Bryan Reed", image: "ryan_reid.png" },
  { name: "Brian Rhoney", image: "rhoney_brian.png" },
  { name: "Derek Rhoney", image: "rhoney_derek.png" },
  { name: "Rick Richmond", image: "richmond_rick.png" },
  { name: "Bill Ripken", image: "ripken_bill.png" },
  { name: "Cal Ripken Jr.", image: "ripken_cal.jpg" },
  { name: "Bob Russett", image: "russett_bob.png" },
  { name: "Nolan Ryan", image: "ryan_nolan.jpg" },
  { name: "Reid Ryan", image: "missing_image.png" },
  { name: "Alan Saliwanchik", image: "saliwanchik_alan.png" },
  { name: "Jim Sardano", image: "sardano_jim.png" },
  { name: "Joe Sardano", image: "sardano_joe.png" },
  { name: "Jamie Savage", image: "savage_jamie.png" },
  { name: "Gary Schloss", image: "schloss_gary.png" },
  { name: "Steve Schnake", image: "schnake_steve.png" },
  { name: "Jake Schroepfer", image: "schroepfer_jake.png" },
  { name: "Ken Schrom", image: "schrom_ken.jpg" },
  { name: "Bob Schuler", image: "schuler_bob.png" },
  { name: "Rich Scott", image: "scott_rich.png" },
  { name: "Katie Seidel", image: "seidel_katie.jpeg" },
  { name: "Nate Seidel", image: "seidel_nate.png" },
  { name: "Mickey Shaw", image: "shaw_mickey.png" },
  { name: "Rick Shaw", image: "shaw_rick.png" },
  { name: "Mike Sheel", image: "sheel_mike.png" },
  { name: "Jeff Shifrin", image: "shifrin_jeff.png" },
  { name: "Dan Short", image: "short_dan.png" },
  { name: "Gracie Simendinger", image: "simendinger_gracie.png" },
  { name: "Mark Simendinger", image: "simendinger_mark.png" },
  { name: "Ted Simendinger", image: "simendinger_ted.png" },
  { name: "Tommy Simendinger", image: "simendinger_tommy.png" },
  { name: "George Simmons", image: "simmons_george.png" },
  { name: "Gary Singleton", image: "singleton_gary.png" },
  { name: "Tod Sizemore", image: "sizemore_tod.png" },
  { name: "Christian Smith", image: "smith_christian.png" },
  { name: "Paul South", image: "south_paul.png" },
  { name: "Rennie Smith", image: "smith_rennie.png" },
  { name: "Ricky Sparks", image: "sparks_ricky.png" },
  { name: "Mike Steffgen", image: "steffgen_mike.png" },
  { name: "TJ Steffgen", image: "steffgen_tj.jpg" },
  { name: "Zac Steffgen", image: "nbbclogo.png" },
  { name: "Tim Stoddard", image: "missing_image.png" },
  { name: "Ben Strauss", image: "strauss_ben.png" },
  { name: "Jay Strauss", image: "strauss_jay.png" },
  { name: "Robb Struckel", image: "struckel_robb.png" },
  { name: "Brave Stuart", image: "stuart_brave.png" },
  { name: "Dave Stuart", image: "stuart_dave.png" },
  { name: "Tom Sudkamp", image: "sudkamp_tom.png" },
  { name: "Gary Sullivan", image: "sullivan_gary.png" },
  { name: "Doug Sutton", image: "sutton_doug.png" },
  { name: "Greg Swallow", image: "swallow_greg.png" },
  { name: "Andy Tarnoff", image: "tarnoff_andy.png" },
  { name: "Todd Tatham", image: "tatham_todd.png" },
  { name: "Scott Tayloe", image: "tayloe_scott.png" },
  { name: "Brandon Tecklenburg", image: "tecklenburg_brandon.png" },
  { name: "Charlie Thomas", image: "thomas_charlie.png" },
  { name: "Joe Tomaselli", image: "tomaselli_joe.png" },
  { name: "Jay Tucker", image: "tucker_jay.png" },
  { name: "Clint Vaughn", image: "vaughn_clint.png" },
  { name: "Harry Vaughn", image: "vaughn_harry.png" },
  { name: "Sasha Vidyaev", image: "vidyaev_sasha.png" },
  { name: "Pete Vlasses", image: "vlasses_pete.png" },
  { name: "Chris Vlasses", image: "nbbclogo.png" },
  { name: "Jim Wadley", image: "wadley_jim.png" },
  { name: "Marty Wadley", image: "wadley_marty.png" },
  { name: "Chris Walwrath", image: "walwrath_chris.png" },
  { name: "Ash Watson", image: "watson_ash.png" },
  { name: "Dave Watson", image: "watson_dave.png" },
  { name: "Chris Wendel", image: "wendel_chris.png" },
  { name: "Jon Whoriskey", image: "nbbclogo.png" },
  { name: "Shawn Whoriskey", image: "nbbclogo.png" },
  { name: "Malcolm White", image: "white_malcolm.png" },
  { name: "Drew Wilcox", image: "wilcox_drew.png" },
  { name: "Mark Wilcox", image: "wilcox_mark.png" },
  { name: "JT Williamson", image: "williamson_jt.png" },
  { name: "Mike Wilson", image: "wilson_mike.png" },
  { name: "Bret Wolfe", image: "wolfe_bret.png" },
  { name: "Tom Wolff", image: "wolff_tom.png" },
  { name: "Mike Womack", image: "womack_mike.png" },
  { name: "Andy Wydler", image: "wydler_andy.png" },
  { name: "Roger Wydler", image: "wydler_roger.png" },
  { name: "Dan Zapatka", image: "zapatka_dan.png" },
  { name: "Dan Zimmer", image: "zimmer_dan.png" }
];

// Function to render all members
function renderAllMembers() {
  const membersGrid = document.querySelector('.members-grid');
  if (!membersGrid) return;
  
  // Clear existing content (except the first few that are hardcoded)
  membersGrid.innerHTML = '';
  
  // Generate member tiles
  membersData.forEach((member, index) => {
    const memberTile = document.createElement('div');
    memberTile.className = 'member-tile';
    memberTile.setAttribute('data-aos', 'fade-up');
    memberTile.setAttribute('data-aos-delay', (index % 6) * 50);
    
    memberTile.innerHTML = `
      <img src="img/members/${member.image}" alt="${member.name}" onerror="this.src='img/members/missing_image.png'">
      <h4>${member.name}</h4>
    `;
    
    membersGrid.appendChild(memberTile);
  });
  
  // Update member count
  const memberCount = document.querySelector('.text-center.mt-5 p');
  if (memberCount) {
    memberCount.textContent = `Showing all ${membersData.length} No Bats Baseball Club members`;
  }
  
  // Refresh AOS animations if available
  if (typeof AOS !== 'undefined') {
    AOS.refresh();
  }
}

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', function() {
  // Render all members on page load
  if (typeof renderAllMembers === 'function') {
    renderAllMembers();
  }
}); 